version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - echo installing nginx
      - sudo apt-get install nginx -y 
  build:
    commands:
      - echo Build has started `date`
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
